### ISSUE TITLE
Update requirements are not met

### ISSUE THREAD

**Issue by dosch** [YunoHost-Apps/miniflux_ynh#21]
- Hardware: *VPS bought online*
- YunoHost version: 4.4.2.7 (stable).
- I have access to my server: *Through SSH & through the webadmin*
- Using, or trying to install package version/branch: 
- If upgrading, current package version: *can be found in the admin, or with `yunohost app info $app_id`*

### Steps to reproduce
   1. *Go to Sysytem update
   2. *Click on 'Upgrade' for miniflux

<img width="1131" alt="Screenshot 2022-08-18 at 12 56 55" src="https://user-images.githubusercontent.com/5372610/185378955-37da35ac-712e-42f6-906d-dfca706ffa1d.png">

3. See error:
`Requirements are not met for miniflux, the package yunohost (4.4.2.7) must be >= 11.0.9`

<img width="800" alt="Screenshot 2022-08-18 at 12 57 15" src="https://user-images.githubusercontent.com/5372610/185379004-49d2f0b8-a6ce-4687-8967-1b1e402fae90.png">

**Comment by ericgaspar** [comment]
YunoHost 11.0.9.7 (Bullseye) is now the last stable version on YunoHost. Perhaps you should upgrade your server?

**Comment by dosch** [comment]
thnx @ericgaspar, I missed that one. As this is a whole migration, I will take the time to do this...
