### ISSUE TITLE
SSO doesn't work

### ISSUE THREAD

**Issue by nqb** [YunoHost-Apps/miniflux_ynh#25]
### Describe the bug

Hello,
I did a fresh installation using 7.5.2~ynh1 on YunoHost 11.0.10.2 without public access.
After installation, SSO doesn't work.
I need to enter username/password I defined during post-installation in order to use application.

### Expected behavior

Click on app on SSO portal and access to Miniflux without any password to enter.

**Comment by ericgaspar** [comment]
This is because SSO is not supported (as far as I know)
