### ISSUE TITLE
App user

### ISSUE THREAD

**Issue by turtaf** [YunoHost-Apps/miniflux_ynh#6]
When going to the miniflux page on my yunohost, I'm asked with username and password and the ones of my yunohost user won't do the job.
Is there a default user or something I'm doing wrong?

**Comment by ericgaspar** [comment]
The admin name and password are to be chosen during install.

**Comment by sphinxc0re** [comment]
I cannot login. I tried every possible combination of my username and all the passwords that I have available.

**Comment by ericgaspar** [comment]
I just installed Miniflux to see if I can reproduce your issue. I have no problem logging into Miniflux with the username and password defined during installation.
Maybe providing some logs would help to debbug... (see in the webadmin > Services > Miniflux)

**Comment by sphinxc0re** [comment]
But I'm not given any input to set the username during the installation. I'm only given the admin _account_ and a separate password and I tried both of those

**Comment by ericgaspar** [comment]
You can see the username and password in the config file `/var/www/miniflux/miniflux.conf`

**Comment by sphinxc0re** [comment]
Okay, my installation was broken so I couldn't look into the file. Now that I did I can confirm that none of my combinations work. I tried the username from the config with several passwords and it did not let me in.
